### ISSUE TITLE
Bundler on .Net 4.7

### ISSUE THREAD

**Issue by swcarter007** [Taritsyn/BundleTransformer#2]
We updated to .net 4.7 creators update for windows 10, and now we are getting SASS and Javascript bundling errors where it says an "Object reference not set to an instance of an object."  

Everything works fine when using a previous .net framework version, and was wondering if you have experienced any issues related to the .net 4.7 specific version.

I should add that the error seems like it happens only on a mobile version of the website, and a separate project for our desktop site behaves fine.

**Comment by Taritsyn** [comment]
Hello!

Send to me a full error message with stack trace.

**Comment by swcarter007** [comment]
The error is happening when the SassAndScssTranslator.cs  is calling LibSassHost.SassCompiler.cs  which is calling the  LibSassHost.Native.SassNativeCompiler.cs file.


The line calling the native compile is

this._sassNativeCompiler.Compile(sassDataContext2);


This seems to be failing when calling the SassNativeCompiler.FillUnmanagedContextOptions function.  From what I can gather, the issue is happening when trying to call a Scss file that uses imports, whereas calling one without imports doesn't have the issue.  Let me know if you need more information.  I know you wanted the stack trace, but the computer that this happened on isn't the same one as I have my email client so I had to type out everything.

________________________________

**Comment by Taritsyn** [comment]
> this._sassNativeCompiler.Compile(sassDataContext2);

It seems, that you are using an old version of the BundleTransformer.SassAndScss. Try upgrading to latest versions of the Bundle Transformer's modules.

**Comment by swcarter007** [comment]
Object reference not set to an instance of an object.
   at BundleTransformer.SassAndScss.Translators.SassAndScssTranslator.InnerTranslate(IAsset asset, CompilationOptions sassOptions, Boolean enableNativeMinification)
   at BundleTransformer.SassAndScss.Translators.SassAndScssTranslator.Translate(IAsset asset)
   at Mobile.Sass.CrateSassTranslator.InnerTranslate(IAsset asset, ITranslator translator, Boolean enableNativeMinification) in C:\tfs\Trunk\Mobile\App_Start\Sass\SassTranslator.cs:line 45

Object reference not set to an instance of an object.
   at Mobile.CrateVirtualPathProvider.FileExists(String virtualPath) in C:\tfs\Trunk\Mobile\App_Start\CrateVirtualPathProvider.cs:line 16
   at BundleTransformer.SassAndScss.Internal.VirtualFileManager.FileExists(String path)
   at LibSassHost.Internal.Native.Sass_Api.sass_compile_data_context(Sass_Data_Context ctx)
   at LibSassHost.Internal.SassCompilerProxy.Compile(SassDataContext dataContext)
   at LibSassHost.SassCompiler.InnerCompile(String content, Boolean indentedSyntax, String inputPath, String outputPath, String sourceMapPath, CompilationOptions options)
   at LibSassHost.SassCompiler.Compile(String content, String inputPath, String outputPath, String sourceMapPath, CompilationOptions options)
   at BundleTransformer.SassAndScss.Translators.SassAndScssTranslator.InnerTranslate(IAsset asset, CompilationOptions sassOptions, Boolean enableNativeMinification)






________________________________

**Comment by Taritsyn** [comment]
>  `at Mobile.CrateVirtualPathProvider.FileExists(String virtualPath) in C:\tfs\Trunk\Mobile\App_Start`

You are using your own VirtualPathProvider?

**Comment by swcarter007** [comment]
Yes, it is parsing through a list of virtual files to return them if the current request matches those files.  I think the error may be occurring in there where it is returning back an exception instead of returning the file.

________________________________

**Comment by swcarter007** [comment]
The issue was in a recent Microsoft release that was using the wrong cache expiration.   
https://github.com/Microsoft/referencesource/blob/master/System.Web/Cache/cache.cs

       ` public void Insert(string key, object value, CacheDependency dependencies, DateTime absoluteExpiration, TimeSpan slidingExpiration) {
            DateTime utcAbsoluteExpiration = DateTimeUtil.ConvertToUniversalTime(absoluteExpiration);
            ObjectCache.Insert(key, value, new CacheInsertOptions() {
                                                Dependencies = dependencies,
                                                AbsoluteExpiration = absoluteExpiration,
                                                SlidingExpiration = slidingExpiration
                                            });
        }`
